name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - "content/**"
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: ["lint:check", "test", "build"]
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn ${{ matrix.step }}

  deploy-preview:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.action != 'closed'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js application
        run: yarn build

      - uses: permaweb/permaweb-deploy@v0.0.2
        with:
          deploy-key: ${{ secrets.DEPLOY_KEY }}
          arns-name: ${{ secrets.ARNS_NAME }}
          preview: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-folder: ./dist
          ttl-seconds: "60"
